name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME1 }}
          password: ${{ secrets.DOCKER_PASSWORD  }}

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-hola-mundo:latest .

      - name: Subir imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-hola-mundo:latest

      - name: Desplegar en Render
        run: curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
